# Generated by Django 4.1 on 2023-05-12 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "cardId",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userId",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="Cartas.card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("cardType", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usercards",
                        to="Cartas.user",
                    ),
                ),
            ],
        ),
    ]
