# Generated by Django 4.1 on 2023-05-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("useriD", models.CharField(max_length=200)),
                (
                    "cardId",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("cardType", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                (
                    "cardId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Cartas.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cartas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("useriD", models.ManyToManyField(to="Cartas.user")),
            ],
        ),
    ]
