# Generated by Django 4.1 on 2023-05-11 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cartas", "0002_user_cartas_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartas",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Cartas.user",
            ),
        ),
    ]
